version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:156962844638:task-definition/892867_pension-detail:7"
        LoadBalancerInfo:
          ContainerName: "892867_pension-detail"
          ContainerPort: "8200"
        PlatformVersion: "LATEST"