version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:156962844638:task-definition/892867_authorization:9"
        LoadBalancerInfo:
          ContainerName: "892867_authorization"
          ContainerPort: "8100"
        PlatformVersion: "LATEST"